#!/usr/bin/env bash
# Copyright (C) 2018 Grzegorz Wcisło

main() {
    init
    while :; do
        draw
        read -rsn1 -d ''
        case "${REPLY}" in
            w) y=$(echo "$y $scale" | awk '{printf "%f", $1+3/$2}') ;;
            s) y=$(echo "$y $scale" | awk '{printf "%f", $1-3/$2}') ;;
            d) x=$(echo "$x $scale" | awk '{printf "%f", $1+6/$2}') ;;
            a) x=$(echo "$x $scale" | awk '{printf "%f", $1-6/$2}') ;;
            q) scale=$(echo "$scale" | awk '{printf "%f", $1/1.1}') ;;
            e) scale=$(echo "$scale" | awk '{printf "%f", $1*1.1}') ;;
            j) switch_fractal ;;
            ?) cleanup ;;
        esac
    done
}

init() {
    resize

    x=-0.5
    y=0
    scale=$DEFAULT_SCALE
    max_iter=100
    fractal=m

    tput smcup
    tput civis
    tput clear

    trap 'resize; draw' WINCH
    trap cleanup INT
}

resize() {
    w=$(tput cols)
    h=$(tput lines)
    DEFAULT_SCALE=$h
}

draw() {
    tput cup 0 0
    ${BASH_SOURCE[0]}.out $fractal $w $h $scale $x $y $max_iter $px $py
    show_debug
}

show_debug() {
    tput cup 0 0
    echo "Position: ($x,$y)"
    echo "Zoom: $scale"
    if [ $fractal = j ]; then
        echo "Parameter: ($px,$py)"
    fi
}

switch_fractal() {
    if [ $fractal = m ]; then
        fractal=j
        px=$x
        py=$y
        m_scale=$scale;
        x=0
        y=0
        scale=$DEFAULT_SCALE
    else
        fractal=m
        x=$px
        y=$py
        scale=$m_scale
    fi
}

cleanup() {
    tput rmcup
    tput cnorm
    exit 0
}

main

